### ISSUE TITLE
JavaScript target 

### ISSUE THREAD

**Issue by darky** [Robert4S/gleam_ref#1]
Would be good to support JavaScript target too 👍 
It shouldn't be difficult, because of JavaScript is mutable 😁

**Comment by Robert4S** [comment]
> Would be good to support JavaScript target too 👍 It shouldn't be difficult, because of JavaScript is mutable 😁

The plan was to make something that works on both platforms without any extra hassle, but I'm not sure how to specify implementations for different targets.

**Comment by darky** [comment]
If you don't know JavaScript, I can provide PR sometimes later, no problem

**Comment by Robert4S** [comment]
You're welcome to make a PR, but the issue was more not knowing how to specify in gleam two different implementations (both written in gleam) for the same function on different targets, since gleam doesn't have macros. I think doing a full JavaScript extern might be necessary if it's not possible though.

**Comment by darky** [comment]
Firstly, need to move away Erlang specific types from public. Need to provide some common type for Erlang and JavaScript, which platform agnostic.

https://github.com/Robert4S/gleam_ref/blob/8dc9ad29e6d2cdcb7748d41cf790c95f249df421/src/ref.gleam#L40

Secondary, some examples, how to FFI to JavaScript 

https://github.com/darky/gluple/blob/e8e140491e3f2dd81ee2566a471a4c46d435df96/src/gluple_ffi.mjs

https://github.com/darky/gluple/blob/e8e140491e3f2dd81ee2566a471a4c46d435df96/src/gluple/reflect.gleam#L39-L57

**Comment by Robert4S** [comment]
I still don't see how I could do target specific implementations without doing them completely in the target languages. Ideally, I would do the BEAM implementation in gleam, and the JS implementation in JS, as I know exactly 0 erlang, but I don't see how that is possible. A PR would be greatly appreciated even if it is just a demonstration of how to achieve these kinds of target specific implementations. Would it be viable to dump the currently generated erlang into a erlang ffi and just use that as an extern rather than writing the implementations in gleam?

**Comment by darky** [comment]
Erlang implementation can be written on Gleam and JS implementation should be written on JS
Mostly it will be looks like it looks right now, only few JS externals will be added and JS file too

```gleam
/// Used for extracting the held data in a RefCell.
/// Once the value has been extracted with this function, any mutations on the Cell will not affect the data already extracted.
@external(javascript, "./ref_ffi.mjs", "get")
pub fn get(cell: RefCell(a)) -> a {
  actor.call(cell.state, Get(_), 10)
}

/// Used for setting the inner value of a RefCell
@external(javascript, "./ref_ffi.mjs", "set")
pub fn set(cell: RefCell(a), contents: a) {
  actor.send(cell.state, Set(contents))
}
```

On JS side need to expose `get`, `set` functions which deals with some shared `Map` under hood

I can add PR on future, but don't promise that it will be near future, incredible busy on work period now :)

**Comment by Robert4S** [comment]
Still confused on how the RefCell type exposed in gleam should look then

**Comment by Robert4S** [comment]
the only problem was the handle_ref function which the compiler was complaining about not having a JS implementation, even though it is never called on the JS target. fixed by just adding a dummy function for it.
